config/routes.rb
Rails.application.routes.draw do
  root "members#home"
  devise_for :users
  resources :fees

  resources :members

  resources :houses do
    resources :members
    resources :fees
  end

end

app/models/fee.rb
class Fee < ActiveRecord::Base
	belongs_to :house
	#after_create :generate_fee_number
	after_create :toatl_amount_fee

	def generate_fee_number
		self.payment_number=self.house.houseNo.to_s + "_" + self.id.to_s
		self.save
	end

	def toatl_amount_fee
		self.total_amount=self.total_amount.to_i + self.amount.to_i
		self.save
	end

end

app/models/house.rb
class House < ActiveRecord::Base
	has_many :members
	has_one :fee
end

app/models/member.rb
class Member < ActiveRecord::Base
	belongs_to :house
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_fee, only: [:show, :edit, :update, :destroy]

  # GET /fees
  # GET /fees.json
  def index
    @fees = Fee.all
  end

  # GET /fees/1
  # GET /fees/1.json
  def show
  end

  # GET /fees/new
  def new
    @fee = Fee.new
    @house = House.find(params[:house_id])
  end

  # GET /fees/1/edit
  def edit
  end

  # POST /fees
  # POST /fees.json
  def create
    @fee = Fee.new(fee_params)

    respond_to do |format|
      if @fee.save
        format.html { redirect_to house_path(@fee.try(:house).try(:id))}
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1
  # PATCH/PUT /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to @fee }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1
  # DELETE /fees/1.json
  def destroy
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to fees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @fee = Fee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fee_params
      params.require(:fee).permit(:house_id, :amount, :last_paid_date, :total_amount, :pending_amount, :payment_number)
    end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
    @fee = Fee.new
  end

  # GET /houses/new
  def new
    @house = House.new
    @fees = @house.fees.build
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house}
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:houseNo, :houseName, :street1, :street2, :city, :state, :pincode, :pattikar_name)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to house_path(@member.house.id)}
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:firstName, :lastName, :DOB, :age, :relationType, :education, :profession, :mobile, :email, :house_id, :vaniyanType, :tharavad, :perneBenefit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/fees/_form.html.erb
<%= form_for(@fee) do |f| %>
  <% if @fee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fee.errors.count, "error") %> prohibited this fee from being saved:</h2>

      <ul>
      <% @fee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="fees">
  <form class="col s12" > 
  <%= f.hidden_field :house_id, value: @house.id  %>  
<!--<div class="row">
    <div class="input-field col s2">
    <%= f.label :house_id %><br>
    <%= f.number_field :house_id %>
  </div> 
  <%= f.fields_for :houses do |a| %>

  <div class="input-field col s2">
    <%= a.label :houseNo, 'House No' %><br>
    <%= a.text_field :houseNo %>
  </div>

  <% end %> -->

  <div class="row">
    <div class="input-field col s10">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
</div>
<!--  <div class="field">
    <%= f.label :last_paid_date %><br>
    <%= f.date_select :last_paid_date %>
  </div>
  <div class="field">
    <%= f.label :total_amount %><br>
    <%= f.number_field :total_amount %>
  </div>
  <div class="field">
    <%= f.label :pending_amount %><br>
    <%= f.number_field :pending_amount %> 
  </div> -->
  <div class="input-field col s3">

    
    <%= f.submit 'Submit' , :class => 'btn waves-effect waves-light' %>
  </div>
<% end %>
</form>
</div>

app/views/fees/edit.html.erb
<h1>Editing fee</h1>

<%= render 'form' %>

<%= link_to 'Show', @fee %> |
<%= link_to 'Back', fees_path %>

app/views/fees/index.html.erb
<button class="btn waves-effect waves-light" align="right"><%= link_to 'Pay Vanthiga', new_fee_path %></button>
<table id="feesList">
  <thead>
    <tr>
      <th>Payment No</th>
      <th>Houseid</th>
      <th>Amount</th>
      <th>Last paid date</th>
      <th>Total amount</th>
      <th>Pending amount</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @fees.each do |fee| %>
      <tr>
        <td><%= fee.payment_number %></td>
        <td><%= fee.house_id %></td>
        <td><%= fee.amount %></td>
        <td><%= fee.last_paid_date %></td>
        <td><%= fee.total_amount %></td>
        <td><%= fee.pending_amount %></td>
        <td><%= link_to 'Show', fee %><%= link_to 'Edit', edit_fee_path(fee) %><%= link_to 'Destroy', fee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/fees/new.html.erb
<h5 class="heading_main">Vanthiga</h5>

<%= render 'form' %>

<%= link_to 'Back', fees_path %>

app/views/fees/show.html.erb
<p id="notice"><%= notice %></p>

<br />

<h5 class="heading_main">Vanthiga Details</h5>

<br />

<table class="striped bordered centered responsive-table">
  <tbody>

    <tr>

  <td><strong>Payment Number:</strong></td>
   <td><%= @fee.payment_number %></td>

 </tr>
    <tr>

  <td><strong>House Number:</strong></td>
   <td><%= @fee.house.houseNo %></td>

 </tr>
 <tr>

   <td><strong>Amount:</strong></td>
   <td><%= @fee.amount %></td>
</tr>
 <tr>
   <td><strong>Last paid date:</strong></td>
   <td><%= @fee.last_paid_date %></td>
</tr>
 <tr>
   <td><strong>Total amount:</strong></td>
   <td><%= @fee.total_amount %></td>
</tr>
 <tr>
   <td><strong>Pending amount:</strong></td>
   <td><%= @fee.pending_amount %></td>
<tr>
</tbody>
</table>

<%= link_to 'Edit', edit_fee_path(@fee) %> |
<%= link_to 'Back', fees_path %>

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="houses">
  <form class="col s12" >   
<div class="row">
    <div class="input-field col s2">
    <%= f.label :houseNo %><br>
    <%= f.text_field :houseNo %>
  </div>

   <div class="input-field col s4">
    <%= f.label :houseName %><br>
    <%= f.text_field :houseName %>
  </div>
  <div class="input-field col s4">
    <%= f.label :Pattikar %><br>
    <%= f.text_field :pattikar_name %>
  </div>
</div>
  <div class="row">
  <div class="input-field col s4">
    <%= f.label :street1 %><br>
    <%= f.text_field :street1 %>
  </div>

   <div class="input-field col s4">
    <%= f.label :street2 %><br>
    <%= f.text_field :street2 %>
  </div>
</div>
<div class="row">
   <div class="input-field col s3">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

   <div class="input-field col s3">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
   <div class="input-field col s3">
    <%= f.label :pincode %><br>
    <%= f.number_field :pincode %>
  </div>
</div>
<div class="input-field col s3">
  
    <%= f.submit 'Register', :class => 'btn waves-effect waves-light' %>
<% end %>
</div>
</form>
</div>

app/views/houses/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<h5 class="heading_main">House List</h5>
<div class="input-field col s3">

<button class="btn waves-effect waves-light" align="right"><%= link_to 'Register House', new_house_path %></button>
</div>

<table id="housesList">
  <thead>
    <tr>
      <th>Houseno</th>
      <th>Housename</th>
      <th>Pattikar</th>
      <th>Street1</th>
      <th>Street2</th>
      <th>City</th>
      <!-- <th>State</th>
      <th>Pincode</th> -->
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.houseNo %></td>
        <td><%= house.houseName %></td>
        <td><%= house.pattikar_name %></td>
        <td><%= house.street1 %></td>
        <td><%= house.street2 %></td>
        <td><%= house.city %></td>
      <!--  <td><%= house.state %></td>
        <td><%= house.pincode %></td>  -->
        <td><%= link_to 'Show', house %> <%= link_to 'Edit', edit_house_path(house) %> <%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/houses/new.html.erb
<div class="houses">

<h5 class="heading_main">Regisetr New House</h5>
<%= render 'form' %>

<%= link_to 'Back', houses_path %>
</div>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<br />
<button class="btn waves-effect waves-light" style="float: right; margin-left: 5px;"><%= link_to 'Register Member', new_house_member_path(@house.id) %></button>



 <button type="button" class="btn waves-effect waves-light"  style="float: right; margin-left: 5px;" data-toggle="modal" data-target="#myModal" id="add">
                           Pay Vanthiga
 </button>
   <br/>
   <br/>
   <div class="modal fade banner-info animated wow slideInUp" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h6 class="modal-title" id="myModalLabel">Pay Vanthiga</h6>
     </div>
     <div class="modal-body">
       <%= render '/fees/form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<br />

<div class="pcss3t pcss3t-effect-slide-bottom pcss3t-theme-4">
     <input type="radio" name="pcss3t" checked id="tab1" class=" tab-content-first ">
        <label for="tab1"><i class="fa fa-home" aria-hidden="true"></i>House Details</label>
        
        <input type="radio" name="pcss3t" id="tab2" class="tab-content-2">
        <label for="tab2"><i class="fa fa-users" aria-hidden="true"></i>Members</label>
        
        <input type="radio" name="pcss3t" id="tab3" class="tab-content-3">
        <label for="tab3"><i class="fa fa-money" aria-hidden="true"></i>Vanthiga</label> 
        
       


<ul>
  <li class="tab-content tab-content-first typography">
    <h5>House Details </h5>
    <table class="striped bordered centered responsive-table">
      <tbody>
        <tr>

          <td><strong>Houseno:</strong></td>
          <td><%= @house.houseNo %></td>
        </tr>
<tr>
  <td><strong>Housename:</strong></td>
  <td><%= @house.houseName %></td>
</tr>
<tr>
  <td><strong>Pattikar:</strong></td>
  <td><%= @house.pattikar_name %></td>
</tr>
<tr>
  <td><strong>Street1:</strong></td>
  <td><%= @house.street1 %></td>
</tr>
<tr>
  <td><strong>Street2:</strong></td>
  <td><%= @house.street2 %></td>
</tr>
<tr>
          <td><strong>City:</strong></td>
          <td><%= @house.city %></td>
</tr>
<tr>
          <td><strong>State:</strong></td>
          <td><%= @house.state %></td>
</tr>
<tr>
  <td><strong>Pincode:</strong></td>
  <td><%= @house.pincode %> </td>
</tr>
</toby>
</table>
<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>
          </li>
          
          <li class="tab-content tab-content-2 typography">
            <h5 class="heading_main" > List of members </h5>
<table class="striped bordered centered responsive-table">
  <tbody>
    
 <% @house.members.each do |member| %>
 <tr>
   <td>  <%= member.try(:firstName) %> </td>
    <td><%= link_to 'Show', member , :class => 'waves-effect waves-light btn-'%> <%= link_to 'Edit', edit_member_path(member) %> <%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
   <% end %>
 
</table> 
</tbody>
          </li>
          
          <li class="tab-content tab-content-3 typography">
          
           <h5 class="heading_main" > Vanthiga </h5>
                  <table class="striped bordered centered responsive-table">
                   <tbody>
                      <% @house.fees.last(5).reverse.each do |fee| %>
                     <tr>
                      <td> <%= fee.try(:created_at).to_time.strftime("%b %d,%Y") %>
                      <td>  <%= fee.try(:amount) %> </td>

                     </tr>

                     <% end %>
                     
                   </tbody>  
                  </table>

                  <h5 style="float: right;"> Total Amount Paid: <%= @house.fees.sum(:amount) %> </h5> 
          </li>
          
          
        </ul>
</div>

<!--<button id="house_show"> house </button>
<button id="member_show"> member</button>
<button id="fee_show">fee</button>
<div class="house_details">
<table class="striped bordered centered responsive-table">
  <tbody>
    <tr>

  <td><strong>Houseno:</strong></td>
  <td><%= @house.houseNo %></td>
</tr>
<tr>
  <td><strong>Housename:</strong></td>
  <td><%= @house.houseName %></td>
</tr>
<tr>
  <td><strong>Pattikar:</strong></td>
  <td><%= @house.pattikar_name %></td>
</tr>
<tr>
  <td><strong>Street1:</strong></td>
  <td><%= @house.street1 %></td>
</tr>
<tr>
  <td><strong>Street2:</strong></td>
  <td><%= @house.street2 %></td>
</tr>
<tr>
  <td><strong>City:</strong></td>
  <td><%= @house.city %></td>
</tr>
<tr>
  <td><strong>State:</strong></td>
  <td><%= @house.state %></td>
</tr>
<tr>
  <td><strong>Pincode:</strong></td>
  <td><%= @house.pincode %> </td>
</tr>
</toby>
</table>
</div>
<div class="member_details">
 <h5 class="heading_main" > List of members </h5>
<table class="striped bordered centered responsive-table">
  <tbody>
    
 <% @house.members.each do |member| %>
 <tr>
   <td>  <%= member.try(:firstName) %> </td>
    <td><%= link_to 'Show', member , :class => 'waves-effect waves-light btn-'%> <%= link_to 'Edit', edit_member_path(member) %> <%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
   <% end %>
 
</table> 
</tbody>
</div>
<div class="fee_details">

<h5 class="heading_main" > Vanthiga </h5>
<table class="striped bordered centered responsive-table">
  <tbody>
    <% @house.fees.each do |fee| %>
    <tr>
      <td> <%= fee.try(:created_at).to_time.strftime("%b %d,%Y") %>
       <td>  <%= fee.try(:amount) %> </td>

    </tr>
    <% end %>
  </tbody>  
</table> 
</div> -->

app/views/layouts/_footer.html.erb
<div class="footer-copy">
		<div class="container">
			<p class="animated wow zoomIn" data-wow-delay=".5s">&copy 2016 A2Tech. All rights reserved | Design by <a href="http://w3layouts.com/">A2Tech</a></p>
		</div>
	</div>

app/views/layouts/_header.html.erb
 <div class="header">
				
				<div class="banner-info animated wow slideInUp" data-wow-delay="800ms">
					<h3>Perne Shree Muchilot<span> Bhagavathi Temple</span></h3>
				</div>
				<!-- #push_sidebar -->
				
				<div class="top-nav">
					<% if user_signed_in? %>
					<span class="menu">
							<%= image_tag "menu.png" %>
					</span>
					
					<ul class="nav1">
						
						<li class="active"><a href="/">Home</a></li>
						<li><a href="/houses/new">New Registraion</a></li>
						<li><a href="/houses">House List</a></li>
						<li><a href="/members">Members</a></li>
						<li><a href="/fees">Vanthiga</a></li>
						<li><%= link_to "Change your password", edit_user_registration_path %> </li>
						<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>

						<% end %>
					</ul>
					<div class="clearfix"> </div>
					<!-- script-for-menu -->
					 <script>
					   $( "span.menu" ).click(function() {
						 $( "ul.nav1" ).slideToggle( 300, function() {
						 // Animation complete.
						  });
						 });
					</script>
					<!-- /script-for-menu -->
				
				<!-- /#push_sidebar -->
				<div class="clearfix"> </div>
			</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amma</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body >



<%= render "layouts/header" %>
<% if notice %> 
<div class="notice-wrapper"> 
<p class="notice"> 

</p> 
</div> 
<% elsif alert %> 
<div class="notice-wrapper"> 
 
</div> 
<% end %> 
<%=yield %>
<script src="//cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
<%= render "layouts/footer" %>

</body>
</html>

app/views/members/edit.html.erb
<h5 class="heading_main">Editing member</h5>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/home.html.erb
<div class="back">
<div class="banner">
		<div class="container">
			<div class="header">
				<!--<div class="header-left animated wow bounceInLeft" data-wow-delay="800ms">
					<form>
						<input type="text" value="Search Here..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search Here...';}" required="">
						<input type="submit" value="" >
						<div class="clearfix"> </div>
					</form>
				</div>
				<div class="header-left1 animated wow zoomIn" data-wow-delay="800ms">
					<h1><a href="index.html">Walk<span>Where To Go This Summer?</span></a></h1>
				</div>
				<!-- #push_sidebar -->
				
				<!-- /#push_sidebar -->
				<div class="clearfix"> </div>
			</div>
		<!--	<div class="banner-info animated wow slideInUp" data-wow-delay="800ms">
				
				
				
				<div class="social-icons">
					<ul>
						<li><a href="#" class="twitter"></a></li>
						<li><a href="#" class="facebook"></a></li>
						<li><a href="#" class="google"></a></li>
						<li><a href="#" class="p"></a></li>
					</ul>
				</div>
			</div> -->
		</div>
	</div>
</div>

app/views/members/index.html.erb
<h1 class="heading_main">Members details</h1>

<%= link_to 'ADD Member', new_member_path %>

<table id="membersList" class="striped bordered centered responsive-table">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Dob</th>
      <th>Age</th>
     <!-- <th>Relationtype</th> -->
      <th>Education</th>
      <th>Profession</th>
      <th>Mobile</th>
      <th>Email</th>
      <th>House No</th>
      <th>Vaniyan</th>
      <th>Tharavad</th>
     <!-- <th>Pernebenefit</th> -->
      <th>Action</th>

    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr height="10">
        <td><%= member.firstName %></td>
        <td><%= member.lastName %></td>
        <td><%= member.DOB %></td>
        <td><%= member.age %></td>
        <!-- <td><%= member.relationType %></td> -->
        <td><%= member.education %></td>
        <td><%= member.profession %></td>
        <td><%= member.mobile %></td>
        <td><%= member.email %></td>
        <td><%= member.house_id %></td>
        <td><%= member.vaniyanType %></td>
        <td><%= member.tharavad %></td>
        <!-- <td><%= member.perneBenefit %></td> -->
        <td><%= link_to 'Show', member , :class => 'waves-effect waves-light btn-'%> <%= link_to 'Edit', edit_member_path(member) %> <%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h5 class="heading_main">New member</h5>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>
<button class="btn waves-effect waves-light" align="right"><%= link_to 'Register Another Member', new_member_path %></button>
<table class="striped bordered centered responsive-table">
  <tbody>
    <tr>
 <td> <strong>Firstname:</strong></td>
  <td><%= @member.firstName %></td>

    </tr>
    <tr>

   <td><strong>Lastname:</strong></td>
   <td><%= @member.lastName %></td>

</tr>
    <tr>

   <td><strong>Dob:</strong></td>
   <td><%= @member.DOB %></td>

</tr>
    <tr>

  <td> <strong>Age:</strong></td>
  <td> <%= @member.age %></td>

</tr>
    <tr>

   <td><strong>Relationtype:</strong></td>
   <td><%= @member.relationType %></td>

</tr>
    <tr>

   <td><strong>Education:</strong></td>
   <td><%= @member.education %></td>

</tr>
    <tr>

   <td><strong>Profession:</strong></td>
   <td><%= @member.profession %></td>

</tr>
    <tr>

   <td><strong>Mobile:</strong></td>
   <td><%= @member.mobile %></td>
</tr>
    <tr>

   <td><strong>Email:</strong></td>
  <td> <%= @member.email %></td>
</p>
</tr>
    <tr>

   <td><strong>House Number:</strong></td>
  <td> <%= @member.house_id %></td>
</tr>
    <tr>

   <td><strong>Vaniyantype:</strong></td>
   <td><%= @member.vaniyanType %>

</tr>
    <tr>

   <td><strong>Tharavad:</strong></td>
   <td><%= @member.tharavad %></td>

</tr>
    <tr>

   <td><strong>Pernebenefit:</strong></td>
   <td><%= @member.perneBenefit %></td>

<tr>
</tbody>
</table>
<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>